/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package derbyPenaltyBoard;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.FontMetrics;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author nbp184
 */
public class FullScreenHeaderPanel extends javax.swing.JPanel {

    private final Team team;
    private JLabel lblHeader;
    private JLabel lblReviews;
    private JLabel lblTimeouts;
    private Insets insets;
    
    /**
     * Creates new form FullScreenHeaderPanel
     * @param team
     */
    public FullScreenHeaderPanel(Team team) {
        initComponents();
        this.team = team;
        this.setBackground(team.colour);
        this.setLayout(new GridBagLayout());
        lblHeader = new JLabel(team.identifier);
        lblHeader.setFont(lblHeader.getFont().deriveFont(FullScreenOptionsDialog.getHeaderFontSize()));
        lblHeader.setBorder(BorderFactory.createEmptyBorder(
                        FullScreenOptionsDialog.getHeaderPadding(FullScreenOptionsDialog.TOP),
                        FullScreenOptionsDialog.getHeaderPadding(FullScreenOptionsDialog.LEFT),
                        FullScreenOptionsDialog.getHeaderPadding(FullScreenOptionsDialog.BOTTOM),
                        FullScreenOptionsDialog.getHeaderPadding(FullScreenOptionsDialog.RIGHT)));
        if(FullScreenOptionsDialog.isShowingTeamIdentifier()) {
            lblHeader.setForeground(team.getContrast());
        } else {
            lblHeader.setForeground(team.colour);
        }
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        c.anchor = GridBagConstraints.LINE_START;
        c.weightx = 1;
        add(lblHeader, c);
        insets = new Insets(
            FullScreenOptionsDialog.getHeaderPadding(FullScreenOptionsDialog.TOP),
            FullScreenOptionsDialog.getHeaderPadding(FullScreenOptionsDialog.LEFT),
            FullScreenOptionsDialog.getHeaderPadding(FullScreenOptionsDialog.BOTTOM),
            FullScreenOptionsDialog.getHeaderPadding(FullScreenOptionsDialog.RIGHT));
        lblReviews = new JLabel(team.getReviewsString());
        lblReviews.setFont(lblReviews.getFont().deriveFont(FullScreenOptionsDialog.getHeaderFontSize()));
        lblReviews.setForeground(team.getContrast());
        lblReviews.setHorizontalAlignment(JLabel.TRAILING);
        setReviewWidth();
        c = new GridBagConstraints();
        c.gridx = 1;
        c.gridy = 0;
        c.insets = insets;
        c.fill = GridBagConstraints.NONE;
        add(lblReviews, c);
        lblTimeouts = new JLabel(team.getTimeoutString());
        lblTimeouts.setFont(lblTimeouts.getFont().deriveFont(FullScreenOptionsDialog.getHeaderFontSize()));
        lblTimeouts.setForeground(team.getContrast());
        lblTimeouts.setHorizontalAlignment(JLabel.TRAILING);
        setTimeoutWidth();
        c = new GridBagConstraints();
        c.gridx = 2;
        c.gridy = 0;
        c.fill = GridBagConstraints.NONE;
        c.insets = insets;
        add(lblTimeouts, c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public void update() {
        this.setBackground(team.colour);
        lblHeader.setText(team.identifier);
        lblHeader.setFont(lblHeader.getFont().deriveFont(FullScreenOptionsDialog.getHeaderFontSize()));
        lblHeader.setBorder(BorderFactory.createEmptyBorder(
                        FullScreenOptionsDialog.getHeaderPadding(FullScreenOptionsDialog.TOP),
                        FullScreenOptionsDialog.getHeaderPadding(FullScreenOptionsDialog.LEFT),
                        FullScreenOptionsDialog.getHeaderPadding(FullScreenOptionsDialog.BOTTOM),
                        FullScreenOptionsDialog.getHeaderPadding(FullScreenOptionsDialog.RIGHT)));
        insets.top = FullScreenOptionsDialog.getHeaderPadding(FullScreenOptionsDialog.TOP);
        insets.left = FullScreenOptionsDialog.getHeaderPadding(FullScreenOptionsDialog.LEFT);
        insets.bottom = FullScreenOptionsDialog.getHeaderPadding(FullScreenOptionsDialog.BOTTOM);
        insets.right = FullScreenOptionsDialog.getHeaderPadding(FullScreenOptionsDialog.RIGHT);
        lblReviews.setFont(lblReviews.getFont().deriveFont(FullScreenOptionsDialog.getHeaderFontSize()));
        setReviewWidth();
        lblTimeouts.setFont(lblTimeouts.getFont().deriveFont(FullScreenOptionsDialog.getHeaderFontSize()));
        setTimeoutWidth();
        if(FullScreenOptionsDialog.isShowingTeamIdentifier()) {
            lblHeader.setForeground(team.getContrast());
        } else {
            lblHeader.setForeground(team.colour);
        }
        lblReviews.setForeground(team.getContrast());
        lblTimeouts.setForeground(team.getContrast());
    }
    
    public void updateSpinners() {
        lblReviews.setText(team.getReviewsString());
        lblTimeouts.setText(team.getTimeoutString());
    }
    
    private void setReviewWidth() {
        FontMetrics fm = lblReviews.getFontMetrics(lblReviews.getFont());
        int width = fm.stringWidth(Team.getMaxReviewsString()) + 5;
        lblReviews.setMinimumSize(new java.awt.Dimension(width, fm.getHeight()));
        lblReviews.setPreferredSize(new java.awt.Dimension(width, fm.getHeight()));
        lblReviews.setMaximumSize(new java.awt.Dimension(width, fm.getHeight()));
    }

    private void setTimeoutWidth() {
        FontMetrics fm = lblTimeouts.getFontMetrics(lblTimeouts.getFont());
        int width = fm.stringWidth(Team.getMaxTimeoutString()) + 5;
        lblTimeouts.setMinimumSize(new java.awt.Dimension(width, fm.getHeight()));
        lblTimeouts.setPreferredSize(new java.awt.Dimension(width, fm.getHeight()));
        lblTimeouts.setMaximumSize(new java.awt.Dimension(width, fm.getHeight()));
    }
}
