/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package derbyPenaltyBoard;

import java.awt.BorderLayout;
import javax.swing.BorderFactory;

/**
 *
 * @author nbp184
 */
public class FullScreenPanel extends javax.swing.JPanel {

    private final Team team;
    private FullScreenTable tblTeam;
    private int rowClicked;
    
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHeader;
    
    /**
     * Creates new form FullScreenPanel
     * @param team
     */
    public FullScreenPanel(Team team) {
        initComponents();
        this.team = team;
        
        setLayout(new BorderLayout());
        
        lblHeader = new javax.swing.JLabel(team.identifier);
        lblHeader.setFont(lblHeader.getFont().deriveFont(FullScreenOptionsDialog.getHeaderFontSize()));
        lblHeader.setOpaque(true);
        lblHeader.setBackground(team.colour);
        lblHeader.setBorder(BorderFactory.createEmptyBorder(
                        FullScreenOptionsDialog.getHeaderPadding(FullScreenOptionsDialog.TOP),
                        FullScreenOptionsDialog.getHeaderPadding(FullScreenOptionsDialog.LEFT),
                        FullScreenOptionsDialog.getHeaderPadding(FullScreenOptionsDialog.BOTTOM),
                        FullScreenOptionsDialog.getHeaderPadding(FullScreenOptionsDialog.RIGHT)));
        if(FullScreenOptionsDialog.isShowingTeamIdentifier()) {
            lblHeader.setForeground(team.getContrast());
        } else {
            lblHeader.setForeground(team.colour);
        }
        add(lblHeader, BorderLayout.PAGE_START);
        
        tblTeam = new FullScreenTable(team);
        tblTeam.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblTeamMousePressed(evt);
            }
            @Override
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblTeamMouseReleased(evt);
            }
        });
        jScrollPane1 = new javax.swing.JScrollPane(tblTeam);
        jScrollPane1.setBorder(null);
        add(jScrollPane1, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupPlayer = new javax.swing.JPopupMenu();
        miNumber = new javax.swing.JMenuItem();
        miEjected = new javax.swing.JCheckBoxMenuItem();

        miNumber.setText("jMenuItem1");
        miNumber.setEnabled(false);
        popupPlayer.add(miNumber);

        miEjected.setText("Is Ejected");
        miEjected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEjectedActionPerformed(evt);
            }
        });
        popupPlayer.add(miEjected);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void miEjectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEjectedActionPerformed
        team.players.get(rowClicked).isEjected = miEjected.isSelected();
        tblTeam.repaint();
    }//GEN-LAST:event_miEjectedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem miEjected;
    private javax.swing.JMenuItem miNumber;
    private javax.swing.JPopupMenu popupPlayer;
    // End of variables declaration//GEN-END:variables
  
    private void tblTeamMouseReleased(java.awt.event.MouseEvent evt) {                                      
        if(evt.isPopupTrigger() && rowClicked >= 0) {
            miNumber.setText(team.players.get(rowClicked).number);
            miEjected.setSelected(team.players.get(rowClicked).isEjected);
            popupPlayer.show(tblTeam, evt.getX(), evt.getY());
        }
    }                                     

    private void tblTeamMousePressed(java.awt.event.MouseEvent evt) {                                     
        if(tblTeam.isEditing()) {
            tblTeam.getCellEditor().stopCellEditing();
        }
        rowClicked = tblTeam.rowAtPoint(evt.getPoint());
    }
    
    public void updateTable() {
        tblTeam.getMyModel().fireTableDataChanged();
    }

    public void updateHeader() {
        lblHeader.setText(team.identifier);
        lblHeader.setFont(lblHeader.getFont().deriveFont(FullScreenOptionsDialog.getHeaderFontSize()));
        lblHeader.setBackground(team.colour);
        if(FullScreenOptionsDialog.isShowingTeamIdentifier()) {
            lblHeader.setForeground(team.getContrast());
        } else {
            lblHeader.setForeground(team.colour);
        }
    }

    public void updateAll() {
        updateHeader();
        FullScreenCellRenderer renderer = (FullScreenCellRenderer)tblTeam.getCellRenderer(0, 0);
        renderer.resetFont();
        tblTeam.setRowHeight(renderer.getFontMetrics().getHeight()
                + FullScreenOptionsDialog.getRowPadding(FullScreenOptionsDialog.TOP)
                + FullScreenOptionsDialog.getRowPadding(FullScreenOptionsDialog.BOTTOM));
        tblTeam.getMyModel().fireTableStructureChanged();
    }
    
}
