/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package derbyPenaltyBoard;

import javax.swing.JColorChooser;
import javax.swing.JTable;
import javax.swing.table.TableColumn;

/**
 *
 * @author nbp184
 */
public class TeamPanel extends javax.swing.JPanel {

    private Team team;
    private int rowClicked;
    
    /**
     * Creates new form TeamPanel
     */
    public TeamPanel(Team team) {
        initComponents();
        tblTeam.setModel(new TeamTableModel(team));
        tblTeam.setAutoResizeMode(JTable.AUTO_RESIZE_SUBSEQUENT_COLUMNS);
        btnColour.setBackground(team.colour);
        txtIdentifier.setText(team.identifier);
        this.team = team;
        rowClicked = -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupPlayer = new javax.swing.JPopupMenu();
        miNumber = new javax.swing.JMenuItem();
        miEjected = new javax.swing.JCheckBoxMenuItem();
        lblIdentifier = new javax.swing.JLabel();
        txtIdentifier = new javax.swing.JTextField();
        lblColour = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTeam = new javax.swing.JTable();
        btnSort = new javax.swing.JButton();
        btnColour = new javax.swing.JButton();

        miNumber.setText("jMenuItem1");
        miNumber.setEnabled(false);
        popupPlayer.add(miNumber);

        miEjected.setText("Is Ejected");
        miEjected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEjectedActionPerformed(evt);
            }
        });
        popupPlayer.add(miEjected);

        lblIdentifier.setText("Team Identifier:");

        txtIdentifier.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdentifierFocusLost(evt);
            }
        });

        lblColour.setText("Team Colour:");

        tblTeam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTeam.setRowSelectionAllowed(false);
        tblTeam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblTeamMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblTeamMouseReleased(evt);
            }
        });
        tblTeam.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                tblTeamComponentResized(evt);
            }
        });
        jScrollPane1.setViewportView(tblTeam);

        btnSort.setText("Sort");
        btnSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortActionPerformed(evt);
            }
        });

        btnColour.setText(" ");
        btnColour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblIdentifier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdentifier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblColour)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnColour))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSort)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdentifier)
                    .addComponent(txtIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblColour)
                    .addComponent(btnColour))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSort)
                .addGap(6, 6, 6))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblTeamComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tblTeamComponentResized
        TableColumn column = tblTeam.getColumnModel().getColumn(0);
        column.setPreferredWidth(column.getPreferredWidth()*2);
    }//GEN-LAST:event_tblTeamComponentResized

    private void btnSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortActionPerformed
        if(tblTeam.isEditing()) {
            tblTeam.getCellEditor().stopCellEditing();
        }
        ((TeamTableModel)tblTeam.getModel()).sort();
    }//GEN-LAST:event_btnSortActionPerformed

    private void btnColourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColourActionPerformed
        team.colour = JColorChooser.showDialog(this, "Choose Team Colour", btnColour.getBackground());
        btnColour.setBackground(team.colour);
    }//GEN-LAST:event_btnColourActionPerformed

    private void txtIdentifierFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdentifierFocusLost
        team.identifier = txtIdentifier.getText();
    }//GEN-LAST:event_txtIdentifierFocusLost

    private void tblTeamMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTeamMouseReleased
        if(evt.isPopupTrigger() && rowClicked >= 0) {
            miNumber.setText(team.players[rowClicked].number);
            miEjected.setSelected(team.players[rowClicked].isEjected);
            popupPlayer.show(tblTeam, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_tblTeamMouseReleased

    private void tblTeamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTeamMousePressed
        if(tblTeam.isEditing()) {
            tblTeam.getCellEditor().stopCellEditing();
        }
        rowClicked = tblTeam.rowAtPoint(evt.getPoint());
        if(team.players[rowClicked].number.isEmpty()) {
            rowClicked = -1;
        }
    }//GEN-LAST:event_tblTeamMousePressed

    private void miEjectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEjectedActionPerformed
        team.players[rowClicked].isEjected = miEjected.isSelected();
        ((TeamTableModel)tblTeam.getModel()).fireTableDataChanged();
    }//GEN-LAST:event_miEjectedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColour;
    private javax.swing.JButton btnSort;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblColour;
    private javax.swing.JLabel lblIdentifier;
    private javax.swing.JCheckBoxMenuItem miEjected;
    private javax.swing.JMenuItem miNumber;
    private javax.swing.JPopupMenu popupPlayer;
    private javax.swing.JTable tblTeam;
    private javax.swing.JTextField txtIdentifier;
    // End of variables declaration//GEN-END:variables

    public void stopEditing() {
        if(tblTeam.isEditing()) {
            tblTeam.getCellEditor().stopCellEditing();
        }
    }
}
