/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package derbyPenaltyBoard;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author nbp184
 */
public class WebsiteOptionsDialog extends javax.swing.JDialog {
    
    public static final int OK = 0;
    public static final int CANCEL = 1;
    
    private static boolean useProxy = false;
    private static String proxyServer = "";
    private static boolean useProxyAuth = false;
    private static String proxyUser = "";
    private static char[] proxyPassword = {};
    
    public static String showDialog(java.awt.Frame parent, String gameName) {
        WebsiteOptionsDialog dialog = new WebsiteOptionsDialog(parent, true);
        dialog.txtGameName.setText(gameName);
        dialog.setLocationRelativeTo(parent);
        dialog.setVisible(true);
        String rv = null;
        if(dialog.result == OK) {
            rv = dialog.txtGameName.getText();
        }
        dialog.dispose();
        return rv;
    }
    
    public static boolean isUsingProxy() {
        return useProxy;
    }
    
    public static String getProxyServer() {
        return proxyServer;
    }
    
    public static boolean isProxyUsingAuthentication() {
        return useProxyAuth;
    }
    
    public static String getProxyUser() {
        return proxyUser;
    }
    
    public static String getProxyPassword() {
        return String.copyValueOf(proxyPassword);
    }
    
    public static void save() {
        try {
            PrintWriter outFile = new PrintWriter(new File("web.ini"));
            outFile.println(useProxy);
            outFile.println(proxyServer);
            outFile.println(useProxyAuth);
            outFile.println(proxyUser);
            for(char chr : proxyPassword) {
                outFile.print(chr);//encode this
            }
            outFile.println();
            outFile.close();
        } catch (IOException ex) {
            Logger.getLogger(FullScreenOptionsDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public static void load() {
        try {
            BufferedReader inFile = new BufferedReader(new FileReader("web.ini"));
            useProxy = Boolean.parseBoolean(inFile.readLine());
            proxyServer = inFile.readLine();
            useProxyAuth = Boolean.parseBoolean(inFile.readLine());
            proxyUser = inFile.readLine();
            proxyPassword = inFile.readLine().toCharArray();//decode this
            inFile.close();
        } catch (IOException | NumberFormatException ex) {
            ex.printStackTrace(System.out);
        }
    }
    
    private int result;

    /**
     * Creates new form WebsiteOptionsDialog
     */
    private WebsiteOptionsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        chkUseProxy.setSelected(useProxy);
        if(chkUseProxy.isSelected()) {
            chkProxyAuth.setEnabled(true);
            txtProxyServer.setEnabled(true);
            txtProxyServer.setText(proxyServer);
            chkProxyAuth.setSelected(useProxyAuth);
            if(chkProxyAuth.isSelected()) {
                lblProxyUser.setEnabled(true);
                txtProxyUser.setEnabled(true);
                lblProxyPassword.setEnabled(true);
                txtProxyPassword.setEnabled(true);
                txtProxyUser.setText(proxyUser);
                txtProxyPassword.setText(String.copyValueOf(proxyPassword));
            }
        }
        result = CANCEL;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtGameName = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        chkUseProxy = new javax.swing.JCheckBox();
        txtProxyServer = new javax.swing.JTextField();
        chkProxyAuth = new javax.swing.JCheckBox();
        lblProxyUser = new javax.swing.JLabel();
        txtProxyUser = new javax.swing.JTextField();
        lblProxyPassword = new javax.swing.JLabel();
        txtProxyPassword = new javax.swing.JPasswordField();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setTitle("Website Options");

        jLabel1.setText("Game Name:");

        txtGameName.setColumns(20);

        chkUseProxy.setText("Use Proxy");
        chkUseProxy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkUseProxyActionPerformed(evt);
            }
        });

        txtProxyServer.setColumns(30);
        txtProxyServer.setEnabled(false);

        chkProxyAuth.setText("Proxy server needs authentication");
        chkProxyAuth.setEnabled(false);
        chkProxyAuth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkProxyAuthActionPerformed(evt);
            }
        });

        lblProxyUser.setText("Username");
        lblProxyUser.setEnabled(false);

        txtProxyUser.setColumns(10);
        txtProxyUser.setEnabled(false);

        lblProxyPassword.setText("Password");
        lblProxyPassword.setEnabled(false);

        txtProxyPassword.setColumns(10);
        txtProxyPassword.setEnabled(false);

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(chkUseProxy)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtProxyServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtGameName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkProxyAuth)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblProxyPassword)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtProxyPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblProxyUser)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtProxyUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOK)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtGameName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkUseProxy)
                    .addComponent(txtProxyServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkProxyAuth)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProxyUser)
                    .addComponent(txtProxyUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProxyPassword)
                    .addComponent(txtProxyPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnOK))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkUseProxyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkUseProxyActionPerformed
        if(chkUseProxy.isSelected()) {
            chkProxyAuth.setEnabled(true);
            txtProxyServer.setEnabled(true);
            if(chkProxyAuth.isSelected()) {
                lblProxyUser.setEnabled(true);
                txtProxyUser.setEnabled(true);
                lblProxyPassword.setEnabled(true);
                txtProxyPassword.setEnabled(true);
            }
        } else {
            chkProxyAuth.setEnabled(false);
            txtProxyServer.setEnabled(false);
            if(chkProxyAuth.isSelected()) {
                lblProxyUser.setEnabled(false);
                txtProxyUser.setEnabled(false);
                lblProxyPassword.setEnabled(false);
                txtProxyPassword.setEnabled(false);
            }
        }
    }//GEN-LAST:event_chkUseProxyActionPerformed

    private void chkProxyAuthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkProxyAuthActionPerformed
        if(chkProxyAuth.isSelected()) {
            lblProxyUser.setEnabled(true);
            txtProxyUser.setEnabled(true);
            lblProxyPassword.setEnabled(true);
            txtProxyPassword.setEnabled(true);
        } else {
            lblProxyUser.setEnabled(false);
            txtProxyUser.setEnabled(false);
            lblProxyPassword.setEnabled(false);
            txtProxyPassword.setEnabled(false);
        }
    }//GEN-LAST:event_chkProxyAuthActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        doSave();
        result = OK;
        this.setVisible(false);
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        result = CANCEL;
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JCheckBox chkProxyAuth;
    private javax.swing.JCheckBox chkUseProxy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblProxyPassword;
    private javax.swing.JLabel lblProxyUser;
    private javax.swing.JTextField txtGameName;
    private javax.swing.JPasswordField txtProxyPassword;
    private javax.swing.JTextField txtProxyServer;
    private javax.swing.JTextField txtProxyUser;
    // End of variables declaration//GEN-END:variables

    private void doSave() {
        useProxy = chkUseProxy.isSelected();
        if(chkUseProxy.isSelected()) {
            proxyServer = txtProxyServer.getText();
            useProxyAuth = chkProxyAuth.isSelected();
            if(chkProxyAuth.isSelected()) {
                proxyUser = txtProxyUser.getText();
                proxyPassword = txtProxyPassword.getPassword();
            } else {
                proxyUser = "";
                proxyPassword = new char[0];
            }
        } else {
            proxyServer = "";
            useProxyAuth = false;
            proxyUser = "";
            proxyPassword = new char[0];
        }
    }
}
